// Voice library — curated catalog for /voices.
// Each entry maps a Callen-branded persona to an underlying Microsoft
// neural voice. Sample mp3s are pre-generated by scripts/generate-voices.mjs
// from the `sample` text below, using `edgeVoice` + the prosody settings.
//
// Heavy Urdu coverage (ur-PK-AsadNeural + ur-PK-UzmaNeural) plus a smaller
// English spread (US, Indian, British), reflecting the Callen product focus
// on Pakistani telephony. Bilingual code-mix included since real Pakistani
// callers switch mid-sentence.

export type VoiceLanguage = "Urdu" | "English" | "Urdu + English";
export type VoiceAccent =
  | "Pakistani"
  | "Indian"
  | "American"
  | "British"
  | "Bilingual";
export type VoiceGender = "Male" | "Female";
export type VoiceAge = "Young adult" | "Adult" | "Middle aged";
export type VoiceCategory =
  | "Conversational"
  | "Customer Service"
  | "Sales"
  | "Receptionist"
  | "Order Taking"
  | "Healthcare"
  | "Narration"
  | "Concierge";

export type Voice = {
  id: string;
  name: string;
  tagline: string;        // short character description shown on card
  edgeVoice: string;      // Microsoft Edge neural voice (used by generator)
  rate?: string;          // SSML rate e.g. "+10%" or "-5%"
  pitch?: string;         // SSML pitch e.g. "+0Hz"
  language: VoiceLanguage;
  extraLanguages?: VoiceLanguage[];   // for the "+N" overflow chip on cards
  accent: VoiceAccent;
  gender: VoiceGender;
  age: VoiceAge;
  category: VoiceCategory;
  useCases: VoiceCategory[];          // shown in detail sheet
  sample: string;                     // text used by the generator and shown in sheet
  premium?: boolean;
  trending?: boolean;
  audioSrc: string;                   // /voices/<id>.mp3
};

// =============================================================
// Catalog (8 Urdu + 1 bilingual + 5 English = 14 voices)
// =============================================================

export const VOICES: Voice[] = [
  // ---------- Urdu (Pakistani) ----------
  {
    id: "faraz",
    name: "Faraz",
    tagline: "Calm and clear, ideal for order taking",
    edgeVoice: "ur-PK-AsadNeural",
    language: "Urdu",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Male",
    age: "Adult",
    category: "Order Taking",
    useCases: ["Order Taking", "Customer Service", "Conversational"],
    sample:
      "Assalam alaikum, Cheezious mein khush amdeed. Aap ka order lene se pehle, kya main aap ka phone number confirm kar sakta hoon?",
    trending: true,
    audioSrc: "/voices/faraz.mp3",
  },
  {
    id: "bilal",
    name: "Bilal",
    tagline: "Energetic and upbeat, perfect for sales",
    edgeVoice: "ur-PK-AsadNeural",
    rate: "+12%",
    language: "Urdu",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Male",
    age: "Young adult",
    category: "Sales",
    useCases: ["Sales", "Conversational"],
    sample:
      "Ji bilkul, abhi hamare paas family deal chal raha hai. Do large pizza, ek garlic bread, aur ek liter coke. Sirf unees so rupay mein.",
    trending: true,
    audioSrc: "/voices/bilal.mp3",
  },
  {
    id: "imran",
    name: "Imran",
    tagline: "Empathetic support specialist",
    edgeVoice: "ur-PK-AsadNeural",
    rate: "-8%",
    pitch: "-2Hz",
    language: "Urdu",
    accent: "Pakistani",
    gender: "Male",
    age: "Adult",
    category: "Customer Service",
    useCases: ["Customer Service", "Conversational"],
    sample:
      "Mujhe afsos hai ke aap ko yeh masla pesh aaya. Main abhi aap ka order check karta hoon, ek minute. Aap fikr na karen, hum is ko theek kar denge.",
    audioSrc: "/voices/imran.mp3",
  },
  {
    id: "saad",
    name: "Saad",
    tagline: "Warm and welcoming, hotel concierge tone",
    edgeVoice: "ur-PK-AsadNeural",
    rate: "-4%",
    language: "Urdu",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Male",
    age: "Middle aged",
    category: "Concierge",
    useCases: ["Concierge", "Receptionist"],
    sample:
      "Khush amdeed, Pearl Continental hotel. Aap ki booking ke liye shukria. Kya aap ki check-in ki tareekh aaj hai, ya kal ke liye plan hai?",
    audioSrc: "/voices/saad.mp3",
  },
  {
    id: "ayesha",
    name: "Ayesha",
    tagline: "Friendly receptionist, soft and clear",
    edgeVoice: "ur-PK-UzmaNeural",
    language: "Urdu",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Female",
    age: "Young adult",
    category: "Receptionist",
    useCases: ["Receptionist", "Customer Service", "Conversational"],
    sample:
      "Assalam alaikum, Callen office mein khush amdeed. Main aap ki kya madad kar sakti hoon? Aap kis department se baat karna chahti hain?",
    trending: true,
    audioSrc: "/voices/ayesha.mp3",
  },
  {
    id: "fatima",
    name: "Fatima",
    tagline: "Warm clinic receptionist",
    edgeVoice: "ur-PK-UzmaNeural",
    rate: "-6%",
    language: "Urdu",
    accent: "Pakistani",
    gender: "Female",
    age: "Adult",
    category: "Healthcare",
    useCases: ["Healthcare", "Receptionist"],
    sample:
      "Lahore Smile Clinic. Aap ka appointment Dr. Imtiaz ke saath agle Mangal ko, dopahar teen baje confirm ho gaya hai. Aap ka shukria.",
    audioSrc: "/voices/fatima.mp3",
  },
  {
    id: "zainab",
    name: "Zainab",
    tagline: "Formal and composed, corporate front desk",
    edgeVoice: "ur-PK-UzmaNeural",
    pitch: "-1Hz",
    language: "Urdu",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Female",
    age: "Adult",
    category: "Conversational",
    useCases: ["Conversational", "Receptionist", "Customer Service"],
    sample:
      "Aap ki call Bank Alfalah ke customer care line par mausool ho gayi hai. Tasdeeq ke liye, kya aap apna chaar adadi shanakhti number share kar saktay hain?",
    audioSrc: "/voices/zainab.mp3",
  },
  {
    id: "nadia",
    name: "Nadia",
    tagline: "Calm and reassuring, healthcare support",
    edgeVoice: "ur-PK-UzmaNeural",
    rate: "-10%",
    pitch: "-1Hz",
    language: "Urdu",
    accent: "Pakistani",
    gender: "Female",
    age: "Middle aged",
    category: "Healthcare",
    useCases: ["Healthcare", "Customer Service"],
    sample:
      "Aap fikr na karen, mein abhi aap ka test result check karti hoon. Doctor sahab ne aap ko follow-up ke liye agle hafte bulaya hai.",
    audioSrc: "/voices/nadia.mp3",
  },

  // ---------- Bilingual (Urdu + English code mix) ----------
  {
    id: "hassan",
    name: "Hassan",
    tagline: "Natural Urdu + English code switch",
    edgeVoice: "ur-PK-AsadNeural",
    language: "Urdu + English",
    extraLanguages: ["Urdu", "English"],
    accent: "Bilingual",
    gender: "Male",
    age: "Young adult",
    category: "Conversational",
    useCases: ["Conversational", "Customer Service", "Sales"],
    sample:
      "Hi, Cheezious order line. Aap ka delivery address Gulberg branch ke under aata hai, right? Estimated time around chalees minutes hai, is that okay?",
    trending: true,
    audioSrc: "/voices/hassan.mp3",
  },

  // ---------- English ----------
  {
    id: "aiden",
    name: "Aiden",
    tagline: "Confident American support voice",
    edgeVoice: "en-US-GuyNeural",
    language: "English",
    accent: "American",
    gender: "Male",
    age: "Adult",
    category: "Customer Service",
    useCases: ["Customer Service", "Sales", "Conversational"],
    sample:
      "Thanks for calling Callen support. I can see your last order right here, and I'll get that resolved for you in just a moment.",
    audioSrc: "/voices/aiden.mp3",
  },
  {
    id: "sara",
    name: "Sara",
    tagline: "Bright and engaging American sales",
    edgeVoice: "en-US-AriaNeural",
    language: "English",
    accent: "American",
    gender: "Female",
    age: "Young adult",
    category: "Sales",
    useCases: ["Sales", "Conversational"],
    sample:
      "Hey, this is Sara from Callen. I noticed you signed up last week. I just wanted to walk you through a couple of features that other Pakistani teams have loved.",
    premium: true,
    audioSrc: "/voices/sara.mp3",
  },
  {
    id: "neerja",
    name: "Neerja",
    tagline: "Warm South Asian English, conversational",
    edgeVoice: "en-IN-NeerjaNeural",
    language: "English",
    extraLanguages: ["Urdu"],
    accent: "Indian",
    gender: "Female",
    age: "Adult",
    category: "Conversational",
    useCases: ["Conversational", "Customer Service", "Receptionist"],
    sample:
      "Good afternoon, you have reached the Callen front desk. May I know how I can direct your call today?",
    trending: true,
    audioSrc: "/voices/neerja.mp3",
  },
  {
    id: "prabhat",
    name: "Prabhat",
    tagline: "Professional South Asian English",
    edgeVoice: "en-IN-PrabhatNeural",
    language: "English",
    extraLanguages: ["Urdu"],
    accent: "Indian",
    gender: "Male",
    age: "Adult",
    category: "Customer Service",
    useCases: ["Customer Service", "Conversational"],
    sample:
      "Hello, this is Prabhat from the Callen team. I understand your concern, and I will help you sort this out within the next two minutes.",
    audioSrc: "/voices/prabhat.mp3",
  },
  {
    id: "sonia",
    name: "Sonia",
    tagline: "Polished British narration",
    edgeVoice: "en-GB-SoniaNeural",
    language: "English",
    accent: "British",
    gender: "Female",
    age: "Adult",
    category: "Narration",
    useCases: ["Narration", "Conversational"],
    sample:
      "Welcome to Callen. The platform that lets Pakistani businesses answer every customer call. In Urdu, in English, at any hour.",
    premium: true,
    audioSrc: "/voices/sonia.mp3",
  },
];

// =============================================================
// Helpers
// =============================================================

export function getVoice(id: string): Voice | undefined {
  return VOICES.find((v) => v.id === id);
}

export const TRENDING_VOICES = VOICES.filter((v) => v.trending);

// Filter chip categories (mirrors the ElevenLabs reference image categories,
// trimmed to what makes sense for Callen).
export const CATEGORY_FILTERS: VoiceCategory[] = [
  "Conversational",
  "Customer Service",
  "Sales",
  "Receptionist",
  "Order Taking",
  "Healthcare",
  "Narration",
  "Concierge",
];

export const LANGUAGE_FILTERS: VoiceLanguage[] = [
  "Urdu",
  "English",
  "Urdu + English",
];

export const ACCENT_FILTERS: VoiceAccent[] = [
  "Pakistani",
  "Indian",
  "American",
  "British",
  "Bilingual",
];

// Use-case feature card surface — bigger tiles below the trending grid.
export type UseCaseCard = {
  id: VoiceCategory;
  title: string;
  blurb: string;
  // Gradient stop colours for the abstract art tile background.
  art: { from: string; via: string; to: string };
};

export const USE_CASE_CARDS: UseCaseCard[] = [
  {
    id: "Customer Service",
    title: "Customer Support",
    blurb: "Empathetic voices that resolve in one turn",
    art: { from: "#0f766e", via: "#134e4a", to: "#022c22" },
  },
  {
    id: "Order Taking",
    title: "Order Taking",
    blurb: "Clear, structured voices for food and retail",
    art: { from: "#b45309", via: "#78350f", to: "#1c1917" },
  },
  {
    id: "Receptionist",
    title: "Reception",
    blurb: "Polite front desk voices, Urdu and English",
    art: { from: "#6d28d9", via: "#4c1d95", to: "#1e1b4b" },
  },
  {
    id: "Sales",
    title: "Sales",
    blurb: "Engaging voices that drive conversions",
    art: { from: "#0f172a", via: "#1e293b", to: "#020617" },
  },
  {
    id: "Healthcare",
    title: "Healthcare",
    blurb: "Reassuring voices for clinics and pharmacies",
    art: { from: "#0e7490", via: "#155e75", to: "#083344" },
  },
  {
    id: "Concierge",
    title: "Hospitality",
    blurb: "Warm voices for hotels and travel",
    art: { from: "#be123c", via: "#881337", to: "#1f1212" },
  },
];
