// Voice library — curated catalog for /voices and the Agent editor.
//
// 16 high-quality pre-generated voices uploaded by the user, branded
// with Pakistani names so the lineup reads as a Pakistani SaaS product.
// Each entry maps a Callen persona to an .mp3 sample sitting in
// /public/voices. Personas cover the full range:
//   - Customer-facing: Hira, Hamza, Ruhaan, Faraz, Sehar, Amna
//   - Sales / outbound: Imran, Bilal
//   - Conversational / personality: Armaan, Roohi, Sana, Aiza
//   - Narration: Tariq, Junaid, Yasir
//   - Collections: Mansoor
//
// edgeVoice is kept as metadata only — these mp3s are pre-rendered, not
// generated by scripts/generate-voices.mjs.

export type VoiceLanguage = "Urdu" | "English" | "Urdu + English";
export type VoiceAccent =
  | "Pakistani"
  | "Indian"
  | "American"
  | "British"
  | "Bilingual";
export type VoiceGender = "Male" | "Female";
export type VoiceAge = "Young adult" | "Adult" | "Middle aged";
export type VoiceCategory =
  | "Conversational"
  | "Customer Service"
  | "Sales"
  | "Receptionist"
  | "Order Taking"
  | "Healthcare"
  | "Narration"
  | "Concierge";

export type Voice = {
  id: string;
  name: string;
  tagline: string;        // short character description shown on card
  edgeVoice: string;      // Microsoft neural voice (informational only)
  rate?: string;
  pitch?: string;
  language: VoiceLanguage;
  extraLanguages?: VoiceLanguage[];
  accent: VoiceAccent;
  gender: VoiceGender;
  age: VoiceAge;
  category: VoiceCategory;
  useCases: VoiceCategory[];
  sample: string;
  premium?: boolean;
  trending?: boolean;
  audioSrc: string;
};

// =============================================================
// Catalog (16 voices)
// Ordered most-business-relevant first so the template round-robin
// fallback lands on safe defaults.
// =============================================================

export const VOICES: Voice[] = [
  // ---------- Customer-facing (clear, professional) ----------
  {
    id: "hira-pro",
    name: "Hira",
    tagline: "Clear, warm and professional",
    edgeVoice: "ur-PK-UzmaNeural",
    language: "Urdu + English",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Female",
    age: "Adult",
    category: "Customer Service",
    useCases: ["Customer Service", "Receptionist", "Conversational"],
    sample:
      "Assalam-o-alaikum, aap ki kis tarah madad kar sakti hoon? Hum yahan din raat aap ke liye hazir hain.",
    trending: true,
    audioSrc: "/voices/hira-pro.mp3",
  },
  {
    id: "hamza-steady",
    name: "Hamza",
    tagline: "Clear and steady",
    edgeVoice: "ur-PK-AsadNeural",
    language: "Urdu + English",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Male",
    age: "Adult",
    category: "Customer Service",
    useCases: ["Customer Service", "Sales", "Conversational"],
    sample:
      "Hello, aap ka issue suna. Main abhi check karta hoon aur do minute mein update deta hoon.",
    trending: true,
    audioSrc: "/voices/hamza-steady.mp3",
  },
  {
    id: "ruhaan",
    name: "Ruhaan",
    tagline: "Clear and confident",
    edgeVoice: "ur-PK-AsadNeural",
    language: "Urdu + English",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Male",
    age: "Young adult",
    category: "Customer Service",
    useCases: ["Customer Service", "Sales"],
    sample:
      "Aap ne sahi number par call kiya hai. Main abhi aap ki query resolve karne mein madad karta hoon.",
    trending: true,
    audioSrc: "/voices/ruhaan.mp3",
  },
  {
    id: "faraz-cheerful",
    name: "Faraz",
    tagline: "Cheerful, natural and soft",
    edgeVoice: "ur-PK-AsadNeural",
    language: "Urdu + English",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Male",
    age: "Adult",
    category: "Conversational",
    useCases: ["Conversational", "Customer Service", "Receptionist"],
    sample:
      "Khush amdeed! Aap ka order hum ne note kar liya hai, aur kuch chahiye?",
    audioSrc: "/voices/faraz-cheerful.mp3",
  },
  {
    id: "sehar-sweet",
    name: "Sehar",
    tagline: "Sweet, lively and warm",
    edgeVoice: "ur-PK-UzmaNeural",
    language: "Urdu + English",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Female",
    age: "Young adult",
    category: "Receptionist",
    useCases: ["Receptionist", "Order Taking", "Customer Service"],
    sample:
      "Hi! Aap ki appointment book ho gayi hai. Reminder time pe SMS aa jaye ga.",
    audioSrc: "/voices/sehar-sweet.mp3",
  },
  {
    id: "amna",
    name: "Amna",
    tagline: "Warm and motherly story voice",
    edgeVoice: "ur-PK-UzmaNeural",
    language: "Urdu + English",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Female",
    age: "Middle aged",
    category: "Healthcare",
    useCases: ["Healthcare", "Receptionist", "Customer Service"],
    sample:
      "Beta, aap fikr na karen. Doctor sahab aap ko bilkul theek kar denge, bharosa rakhen.",
    trending: true,
    audioSrc: "/voices/amna.mp3",
  },

  // ---------- Sales / outbound ----------
  {
    id: "imran-rich",
    name: "Imran",
    tagline: "Rich, confident and expressive",
    edgeVoice: "ur-PK-AsadNeural",
    language: "Urdu + English",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Male",
    age: "Adult",
    category: "Sales",
    useCases: ["Sales", "Customer Service", "Conversational"],
    sample:
      "Aap ka plan renewal hone wala hai. Main aap ko ek behtareen offer dikhata hoon, sirf tees second.",
    trending: true,
    premium: true,
    audioSrc: "/voices/imran-rich.mp3",
  },
  {
    id: "bilal",
    name: "Bilal",
    tagline: "Punchy, crisp and energetic",
    edgeVoice: "ur-PK-AsadNeural",
    rate: "+10%",
    language: "Urdu + English",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Male",
    age: "Young adult",
    category: "Sales",
    useCases: ["Sales", "Conversational"],
    sample:
      "Boss, deal of the century! Aaj hi sign up karen, kal late ho jayega.",
    audioSrc: "/voices/bilal.mp3",
  },

  // ---------- Conversational / personality ----------
  {
    id: "armaan",
    name: "Armaan",
    tagline: "Funny and expressive vlogger",
    edgeVoice: "ur-PK-AsadNeural",
    language: "Urdu + English",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Male",
    age: "Young adult",
    category: "Conversational",
    useCases: ["Conversational", "Sales"],
    sample:
      "Hey what's up everyone! Aaj ka maza alag hi level ka hai, suna do kya chahiye!",
    audioSrc: "/voices/armaan.mp3",
  },
  {
    id: "roohi",
    name: "Roohi",
    tagline: "Breathy, soft and whisper",
    edgeVoice: "ur-PK-UzmaNeural",
    pitch: "-2Hz",
    language: "Urdu + English",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Female",
    age: "Young adult",
    category: "Conversational",
    useCases: ["Conversational", "Narration"],
    sample:
      "Sun rahay hain mujhe? Main yahan hoon, bilkul aap ke saath.",
    premium: true,
    audioSrc: "/voices/roohi.mp3",
  },
  {
    id: "sana",
    name: "Sana",
    tagline: "Warm and emotional companion",
    edgeVoice: "ur-PK-UzmaNeural",
    language: "Urdu + English",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Female",
    age: "Young adult",
    category: "Conversational",
    useCases: ["Conversational"],
    sample:
      "Aap ne phone uthaya, bohat acha laga. Bataiye aaj din kaisa raha?",
    premium: true,
    audioSrc: "/voices/sana.mp3",
  },
  {
    id: "aiza",
    name: "Aiza",
    tagline: "Cute and friendly young voice",
    edgeVoice: "ur-PK-UzmaNeural",
    rate: "-5%",
    language: "Urdu + English",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Female",
    age: "Young adult",
    category: "Conversational",
    useCases: ["Conversational"],
    sample:
      "Hi! Mujhe aap se baat karke acha laga. Kya baat karein gay aaj?",
    premium: true,
    audioSrc: "/voices/aiza.mp3",
  },

  // ---------- Narration ----------
  {
    id: "tariq",
    name: "Tariq",
    tagline: "Storyteller",
    edgeVoice: "ur-PK-AsadNeural",
    rate: "-3%",
    language: "Urdu + English",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Male",
    age: "Adult",
    category: "Narration",
    useCases: ["Narration", "Conversational"],
    sample:
      "Ek waqt tha jab har masla mushkil tha. Phir ek call ne sab kuch badal diya.",
    audioSrc: "/voices/tariq.mp3",
  },
  {
    id: "junaid",
    name: "Junaid",
    tagline: "Faceless true-crime narrator",
    edgeVoice: "ur-PK-AsadNeural",
    rate: "-5%",
    pitch: "-1Hz",
    language: "Urdu + English",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Male",
    age: "Adult",
    category: "Narration",
    useCases: ["Narration"],
    sample:
      "Raat ke gyarah baj rahe the. Phone ki ghanti baji, lekin doosri taraf khamoshi thi.",
    premium: true,
    audioSrc: "/voices/junaid.mp3",
  },
  {
    id: "yasir",
    name: "Yasir",
    tagline: "Cinematic horror storyteller",
    edgeVoice: "ur-PK-AsadNeural",
    rate: "-8%",
    pitch: "-3Hz",
    language: "Urdu + English",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Male",
    age: "Adult",
    category: "Narration",
    useCases: ["Narration"],
    sample:
      "Andheri raat thi. Hawa ruk gayi thi. Aur tabhi ek aawaz aayi, jo kabhi bhulai nahi ja sakti.",
    premium: true,
    audioSrc: "/voices/yasir.mp3",
  },

  // ---------- Collections ----------
  {
    id: "mansoor",
    name: "Mansoor",
    tagline: "Firm collections agent",
    edgeVoice: "ur-PK-AsadNeural",
    language: "Urdu + English",
    extraLanguages: ["English"],
    accent: "Pakistani",
    gender: "Male",
    age: "Adult",
    category: "Customer Service",
    useCases: ["Customer Service", "Sales"],
    sample:
      "Sir, aap ka payment do mahine se pending hai. Aaj clear kar dijiye, ya hum aage badhne ko majboor hain.",
    audioSrc: "/voices/mansoor.mp3",
  },
];

// =============================================================
// Helpers
// =============================================================

export function getVoice(id: string): Voice | undefined {
  return VOICES.find((v) => v.id === id);
}

// Hand-curated template -> voice mapping so each template gets the most
// appropriate persona, not a random round-robin pick. Falls back to the
// first voice (Hira pro) if a template id is missing here.
import { agentTemplates } from "./agent-templates";

const TEMPLATE_VOICE_OVERRIDES: Record<string, string> = {
  "tpl-customer-support":     "hira-pro",        // clear + professional
  "tpl-renewal-expansion":    "imran-rich",      // confident outbound
  "tpl-it-helpdesk":          "hamza-steady",    // calm, patient
  "tpl-it-access":            "ruhaan",          // clear, methodical
  "tpl-technical-support":    "faraz-cheerful",  // patient walk-through
  "tpl-escalated-support":    "amna",            // warm + reassuring
  "tpl-incident-response":    "ruhaan",          // direct + confident
  "tpl-order-tracking":       "sehar-sweet",     // warm retail tone
  "tpl-accounts-receivable":  "mansoor",         // firm collections
  "tpl-internal-knowledge":   "tariq",           // helpful storyteller
  "tpl-legal-intake":         "hamza-steady",    // formal + steady
  "tpl-ecommerce-cx":         "sehar-sweet",     // warm shopping
  "tpl-membership-subscription": "faraz-cheerful", // patient retention
  "tpl-utility-telecom":      "hira-pro",        // professional billing
  "tpl-personal-voice":       "armaan",          // versatile + expressive
};

const TEMPLATE_VOICE_MAP: Map<string, Voice> = (() => {
  const map = new Map<string, Voice>();
  agentTemplates.forEach((t, i) => {
    const overrideId = TEMPLATE_VOICE_OVERRIDES[t.id];
    const voice =
      (overrideId && VOICES.find((v) => v.id === overrideId)) ||
      VOICES[i % VOICES.length];
    map.set(t.id, voice);
  });
  return map;
})();

export function voiceForTemplateId(templateId: string): Voice {
  return TEMPLATE_VOICE_MAP.get(templateId) ?? VOICES[0];
}

export const TRENDING_VOICES = VOICES.filter((v) => v.trending);

// Filter chip categories — only show ones that have voices in them.
const _activeCategories = new Set(VOICES.map((v) => v.category));
export const CATEGORY_FILTERS: VoiceCategory[] = (
  [
    "Customer Service",
    "Sales",
    "Receptionist",
    "Healthcare",
    "Conversational",
    "Narration",
    "Order Taking",
    "Concierge",
  ] as VoiceCategory[]
).filter((c) => _activeCategories.has(c));

export const LANGUAGE_FILTERS: VoiceLanguage[] = [
  "Urdu",
  "English",
  "Urdu + English",
];

const _activeAccents = new Set(VOICES.map((v) => v.accent));
export const ACCENT_FILTERS: VoiceAccent[] = (
  ["Pakistani", "Indian", "Bilingual", "American", "British"] as VoiceAccent[]
).filter((a) => _activeAccents.has(a));

// Use-case feature card surface — bigger tiles below the trending grid.
export type UseCaseCard = {
  id: VoiceCategory;
  title: string;
  blurb: string;
  art: { from: string; via: string; to: string };
};

export const USE_CASE_CARDS: UseCaseCard[] = [
  {
    id: "Customer Service",
    title: "Customer Support",
    blurb: "Calm, clear voices that resolve issues without friction.",
    art: { from: "#bfdbfe", via: "#60a5fa", to: "#1e3a8a" },
  },
  {
    id: "Sales",
    title: "Sales and Renewals",
    blurb: "Confident, persuasive voices that move a conversation forward.",
    art: { from: "#fde68a", via: "#f59e0b", to: "#78350f" },
  },
  {
    id: "Receptionist",
    title: "Receptionist",
    blurb: "Warm, friendly voices for first-line greeting and routing.",
    art: { from: "#fbcfe8", via: "#ec4899", to: "#831843" },
  },
  {
    id: "Healthcare",
    title: "Healthcare",
    blurb: "Empathetic voices for clinics, triage, and patient follow-up.",
    art: { from: "#a7f3d0", via: "#10b981", to: "#064e3b" },
  },
  {
    id: "Conversational",
    title: "Conversational",
    blurb: "Natural, expressive voices for casual back-and-forth.",
    art: { from: "#c7d2fe", via: "#6366f1", to: "#1e1b4b" },
  },
  {
    id: "Narration",
    title: "Narration",
    blurb: "Cinematic, story-telling voices for explainers and previews.",
    art: { from: "#cbd5e1", via: "#64748b", to: "#0f172a" },
  },
];
