// Voices — curated library inspired by the ElevenLabs reference image,
// adapted for Callen's Pakistani telephony focus. Heavy Urdu coverage,
// real playable mp3s generated by scripts/generate-voices.mjs, and a
// detail sheet that wires into the existing agent template picker.

"use client";

import { useMemo, useRef, useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import {
  Search,
  Filter,
  ArrowDownUp,
  Upload,
  Plus,
  ChevronLeft,
  ChevronRight,
  MessageCircle,
  BookOpen,
  Drama,
  Smartphone,
  GraduationCap,
  Megaphone,
  Languages,
  AudioLines,
  Mic2,
} from "lucide-react";

import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  VOICES,
  TRENDING_VOICES,
  USE_CASE_CARDS,
  CATEGORY_FILTERS,
  LANGUAGE_FILTERS,
  ACCENT_FILTERS,
  type Voice,
  type VoiceCategory,
  type VoiceLanguage,
  type VoiceAccent,
} from "@/lib/voice-library";
import { VoiceCard } from "@/components/voices/voice-card";
import { UseCaseCard } from "@/components/voices/use-case-card";
import { VoiceDetailSheet } from "@/components/voices/voice-detail-sheet";

// =============================================================
// Page
// =============================================================

type Tab = "explore" | "my" | "default";

const CATEGORY_ICONS: Record<VoiceCategory, React.ComponentType<{ className?: string }>> = {
  Conversational: MessageCircle,
  "Customer Service": Mic2,
  Sales: Megaphone,
  Receptionist: Smartphone,
  "Order Taking": AudioLines,
  Healthcare: GraduationCap,
  Narration: BookOpen,
  Concierge: Drama,
};

export default function VoicesPage() {
  const [tab, setTab] = useState<Tab>("explore");
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState<VoiceCategory | null>(null);
  const [language, setLanguage] = useState<VoiceLanguage | null>(null);
  const [accent, setAccent] = useState<VoiceAccent | null>(null);
  const [openId, setOpenId] = useState<string | null>(null);
  const useCaseScrollRef = useRef<HTMLDivElement>(null);

  const openVoice = openId ? VOICES.find((v) => v.id === openId) ?? null : null;

  const visibleVoices = useMemo(() => {
    let list = VOICES;
    if (tab === "my") {
      // No user-cloned voices yet — the "My Voices" tab shows just the empty state.
      list = [];
    } else if (tab === "default") {
      // Default voices are the non-premium English ones — feels like a built-in library.
      list = VOICES.filter((v) => !v.premium && v.language === "English");
    }
    if (search) {
      const q = search.toLowerCase();
      list = list.filter(
        (v) =>
          v.name.toLowerCase().includes(q) ||
          v.tagline.toLowerCase().includes(q) ||
          v.category.toLowerCase().includes(q) ||
          v.sample.toLowerCase().includes(q)
      );
    }
    if (category) list = list.filter((v) => v.useCases.includes(category));
    if (language) list = list.filter((v) => v.language === language);
    if (accent) list = list.filter((v) => v.accent === accent);
    return list;
  }, [tab, search, category, language, accent]);

  const trendingFiltered = useMemo(() => {
    // Trending row shows the curated trending picks unless the user has
    // filters applied, in which case we hide the row entirely (the main
    // grid below already covers the filtered result).
    return TRENDING_VOICES;
  }, []);

  const showTrending =
    tab === "explore" &&
    !search &&
    !category &&
    !language &&
    !accent;

  function clearFilters() {
    setCategory(null);
    setLanguage(null);
    setAccent(null);
    setSearch("");
  }

  function scrollUseCases(dir: -1 | 1) {
    useCaseScrollRef.current?.scrollBy({
      left: dir * 320,
      behavior: "smooth",
    });
  }

  return (
    <div className="px-6 lg:px-8 pb-16 pt-6 max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex items-start justify-between gap-4 mb-5">
        <div>
          <h1 className="text-[28px] font-bold tracking-[-0.04em] text-neutral-950">
            Voices
          </h1>
        </div>
        <Button className="rounded-full px-4 h-9 shrink-0 gap-1.5">
          <Plus className="size-4" />
          Create Voice
        </Button>
      </div>

      {/* Tabs */}
      <div className="border-b border-neutral-200 mb-5">
        <div className="flex items-center gap-1">
          <TabButton
            active={tab === "explore"}
            onClick={() => setTab("explore")}
            icon={<AudioLines className="size-4" />}
          >
            Explore
          </TabButton>
          <TabButton
            active={tab === "my"}
            onClick={() => setTab("my")}
          >
            My Voices
          </TabButton>
          <TabButton
            active={tab === "default"}
            onClick={() => setTab("default")}
          >
            Default Voices
          </TabButton>
        </div>
      </div>

      {/* Search + filters row */}
      <div className="flex items-center gap-2 mb-3">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-neutral-400" />
          <Input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search library voices..."
            className="pl-9 pr-10 h-10 rounded-full bg-white"
          />
          <button
            type="button"
            className="absolute right-3 top-1/2 -translate-y-1/2 text-neutral-400 hover:text-neutral-700 transition-colors"
            aria-label="Upload sample"
            title="Upload a sample to find a similar voice"
          >
            <Upload className="size-4" />
          </button>
        </div>
        <Button variant="outline" className="rounded-full h-10 gap-1.5">
          <Filter className="size-4" />
          Filters
        </Button>
        <Button
          variant="outline"
          className="rounded-full h-10 size-10 p-0"
          aria-label="Sort"
        >
          <ArrowDownUp className="size-4" />
        </Button>
      </div>

      {/* Filter chips */}
      <div className="flex items-center gap-1.5 mb-7 overflow-x-auto scrollbar-thin pb-1">
        <LanguageChip
          language={language}
          onChange={setLanguage}
        />
        <AccentChip accent={accent} onChange={setAccent} />
        <div className="h-5 w-px bg-neutral-200 mx-1 shrink-0" />
        {CATEGORY_FILTERS.map((c) => {
          const Icon = CATEGORY_ICONS[c];
          const active = category === c;
          return (
            <button
              key={c}
              type="button"
              onClick={() => setCategory(active ? null : c)}
              className={cn(
                "inline-flex items-center gap-1.5 rounded-full border h-8 px-3 text-[12px] font-medium whitespace-nowrap shrink-0 transition-colors",
                active
                  ? "bg-neutral-950 text-white border-neutral-950"
                  : "bg-white border-neutral-200 text-neutral-700 hover:border-neutral-300 hover:bg-neutral-50"
              )}
            >
              <Icon className="size-3.5" />
              {c}
            </button>
          );
        })}
        <button
          type="button"
          className="size-8 rounded-full border border-neutral-200 bg-white text-neutral-500 hover:text-neutral-900 hover:border-neutral-300 inline-flex items-center justify-center shrink-0"
          aria-label="More categories"
        >
          <ChevronRight className="size-4" />
        </button>
      </div>

      {tab === "my" ? (
        <MyVoicesEmptyState />
      ) : (
        <>
          {/* Trending */}
          {showTrending && (
            <section className="mb-9">
              <SectionHeading title="Trending voices" />
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
                {trendingFiltered.map((v) => (
                  <VoiceCard
                    key={v.id}
                    voice={v}
                    onOpen={(id) => setOpenId(id)}
                  />
                ))}
              </div>
            </section>
          )}

          {/* Handpicked use cases */}
          {showTrending && (
            <section className="mb-9">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-[16px] font-semibold tracking-tight text-neutral-950">
                  Handpicked for your use case
                </h2>
                <div className="flex items-center gap-1">
                  <button
                    type="button"
                    onClick={() => scrollUseCases(-1)}
                    className="size-8 rounded-full border border-neutral-200 bg-white hover:bg-neutral-50 inline-flex items-center justify-center text-neutral-700"
                    aria-label="Scroll left"
                  >
                    <ChevronLeft className="size-4" />
                  </button>
                  <button
                    type="button"
                    onClick={() => scrollUseCases(1)}
                    className="size-8 rounded-full border border-neutral-200 bg-white hover:bg-neutral-50 inline-flex items-center justify-center text-neutral-700"
                    aria-label="Scroll right"
                  >
                    <ChevronRight className="size-4" />
                  </button>
                </div>
              </div>
              <div
                ref={useCaseScrollRef}
                className="flex gap-4 overflow-x-auto scroll-smooth scrollbar-thin pb-2 snap-x snap-mandatory -mx-1 px-1"
              >
                {USE_CASE_CARDS.map((card) => (
                  <div
                    key={card.id}
                    className="snap-start shrink-0 w-[260px] md:w-[300px]"
                  >
                    <UseCaseCard
                      card={card}
                      onSelect={(id) => setCategory(id as VoiceCategory)}
                    />
                  </div>
                ))}
              </div>
            </section>
          )}

          {/* All / filtered library */}
          <section>
            <SectionHeading
              title={
                category || language || accent || search
                  ? `${visibleVoices.length} ${visibleVoices.length === 1 ? "voice" : "voices"} match`
                  : tab === "default"
                  ? "Default voices"
                  : "All voices"
              }
              right={
                (category || language || accent || search) && (
                  <button
                    type="button"
                    onClick={clearFilters}
                    className="text-[12px] font-medium text-neutral-600 hover:text-neutral-900"
                  >
                    Clear filters
                  </button>
                )
              }
            />
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
              <AnimatePresence mode="popLayout">
                {visibleVoices.map((v) => (
                  <motion.div
                    key={v.id}
                    layout
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -4 }}
                    transition={{ duration: 0.18 }}
                  >
                    <VoiceCard voice={v} onOpen={(id) => setOpenId(id)} />
                  </motion.div>
                ))}
              </AnimatePresence>
            </div>
            {visibleVoices.length === 0 && (
              <div className="rounded-3xl border border-dashed border-neutral-200 p-12 text-center">
                <p className="text-[14px] font-medium text-neutral-900">
                  No voices match those filters.
                </p>
                <p className="text-[12px] text-neutral-500 mt-1">
                  Try clearing filters or searching for a different keyword.
                </p>
                <Button
                  variant="outline"
                  className="rounded-full mt-4"
                  onClick={clearFilters}
                >
                  Clear filters
                </Button>
              </div>
            )}
          </section>
        </>
      )}

      <VoiceDetailSheet
        voice={openVoice}
        onOpenChange={(open) => {
          if (!open) setOpenId(null);
        }}
      />
    </div>
  );
}

// =============================================================
// Subcomponents
// =============================================================

function TabButton({
  active,
  onClick,
  icon,
  children,
}: {
  active: boolean;
  onClick: () => void;
  icon?: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        "relative inline-flex items-center gap-1.5 px-3 py-2 text-[13px] font-medium transition-colors",
        active ? "text-neutral-950" : "text-neutral-500 hover:text-neutral-800"
      )}
    >
      {icon}
      {children}
      {active && (
        <motion.span
          layoutId="voicesTab"
          className="absolute -bottom-px left-0 right-0 h-0.5 bg-neutral-950 rounded-full"
        />
      )}
    </button>
  );
}

function SectionHeading({
  title,
  right,
}: {
  title: string;
  right?: React.ReactNode;
}) {
  return (
    <div className="flex items-center justify-between mb-4">
      <h2 className="text-[16px] font-semibold tracking-tight text-neutral-950 inline-flex items-center gap-1.5">
        {title}
        <ChevronRight className="size-4 text-neutral-400" />
      </h2>
      {right}
    </div>
  );
}

function LanguageChip({
  language,
  onChange,
}: {
  language: VoiceLanguage | null;
  onChange: (v: VoiceLanguage | null) => void;
}) {
  return (
    <div className="relative shrink-0">
      <select
        value={language ?? ""}
        onChange={(e) =>
          onChange((e.target.value as VoiceLanguage) || null)
        }
        className={cn(
          "appearance-none rounded-full border h-8 pl-8 pr-7 text-[12px] font-medium cursor-pointer transition-colors",
          language
            ? "bg-neutral-950 text-white border-neutral-950"
            : "bg-white border-neutral-200 text-neutral-700 hover:border-neutral-300"
        )}
      >
        <option value="">Language</option>
        {LANGUAGE_FILTERS.map((l) => (
          <option key={l} value={l}>
            {l}
          </option>
        ))}
      </select>
      <Languages className={cn("absolute left-2.5 top-1/2 -translate-y-1/2 size-3.5 pointer-events-none", language ? "text-white" : "text-neutral-500")} />
      <ChevronDown className={cn("absolute right-2 top-1/2 -translate-y-1/2 size-3.5 pointer-events-none", language ? "text-white" : "text-neutral-500")} />
    </div>
  );
}

function AccentChip({
  accent,
  onChange,
}: {
  accent: VoiceAccent | null;
  onChange: (v: VoiceAccent | null) => void;
}) {
  return (
    <div className="relative shrink-0">
      <select
        value={accent ?? ""}
        onChange={(e) =>
          onChange((e.target.value as VoiceAccent) || null)
        }
        className={cn(
          "appearance-none rounded-full border h-8 px-3 pr-7 text-[12px] font-medium cursor-pointer transition-colors",
          accent
            ? "bg-neutral-950 text-white border-neutral-950"
            : "bg-white border-neutral-200 text-neutral-700 hover:border-neutral-300"
        )}
      >
        <option value="">Accent</option>
        {ACCENT_FILTERS.map((a) => (
          <option key={a} value={a}>
            {a}
          </option>
        ))}
      </select>
      <ChevronDown className={cn("absolute right-2 top-1/2 -translate-y-1/2 size-3.5 pointer-events-none", accent ? "text-white" : "text-neutral-500")} />
    </div>
  );
}

function ChevronDown({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className}
    >
      <polyline points="6 9 12 15 18 9" />
    </svg>
  );
}

function MyVoicesEmptyState() {
  return (
    <div className="rounded-3xl border border-dashed border-neutral-200 p-12 text-center">
      <div className="size-12 mx-auto rounded-2xl bg-neutral-100 flex items-center justify-center mb-3">
        <Mic2 className="size-5 text-neutral-700" />
      </div>
      <h3 className="text-[15px] font-semibold text-neutral-950">
        No cloned voices yet
      </h3>
      <p className="text-[12px] text-neutral-500 mt-1 max-w-sm mx-auto">
        Upload a thirty second sample of any speaker and Callen will clone
        their voice for use on your inbound calls.
      </p>
      <Button className="rounded-full mt-4 gap-1.5">
        <Plus className="size-4" />
        Clone a voice
      </Button>
    </div>
  );
}
